- name: copy logstash configuration
  copy:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: stop logstash
  systemd:
    name: logstash
    state: stopped # restart is taking time so stopping

- name: Wait for 5044 port to be stopped 
  wait_for:
    port: 5044
    delay: 15
    state: stopped

- name: start logstash
  systemd:
    name: logstash
    state: started # restart is taking time so stopping

- name: Wait for 5044 port to be started 
  wait_for:
    port: 5044
    delay: 15
    state: started