- name: Demo on become sudo
  hosts: all
  become: yes
  tasks: 
   - name: Get id of user
     shell: id
     register: out

   - name: print
     debug:
      msg: "{{out}}" 

      # ome can be used on task level also or on play level
      # play level become will run all tasks as root user
      #task level become only that task as root user