- name: Demo on conditions
  hosts: localhost # no need to have ini file we are running in same machine
  vars:
   OS: centos
   NUM: 7
   Bool1: true
  tasks: 
   - name: centOS
     debug:
      msg: CentOs 
     when: OS == "centos"
   - name: Ubuntu
     debug:
      msg: Ubuntu 
     when: OS == "ubuntu" 
   - name: number condition 1
     debug:
      msg: Num con 1
     when: NUM >= 5 
   - name: number condition 2
     debug:
      msg: Num con 2
     when: NUM <= 5 
   - name: if bool1 is true
     debug:
      msg: Bool is true
     #when: Bool1
     when: Bool1 | bool
    # in newer versions it will be written as Bool1 | bool

# in conditions it will bother about each and every task and then validate the task according to the constition and execute that particular task and remaining will be skipped
# difference between number and string is strings are quoted and numbers are not
# here variable would be a starting value defenently and not quoted
