- name: Demo on loops
  hosts: localhost
  tasks:
   - name: print
     debug:
      msg: Hello, {{item}} # same task run for multiple times for different values item is systemdefined one
     loop:
      - John
      - Ram 
   - name: print map
     debug:
      msg: Hello {{item.name}}, weilcome to {{item.course}} course
     loop:
      - { name: john, course: AWS }
      - { name: Ram, course: DevOps }