- name: roboshop project setup - Frontend
  hosts: FRONTEND
  roles:
    - frontend

- name: roboshop project setup - mongodb
  hosts: MONGODB
  roles:
    - mongodb

- name: roboshop project setup - catalogue
  hosts: CATALOGUE
  roles:
    - catalogue

- name: roboshop project setup - Redis
  hosts: REDIS
  roles:
    - redis

- name: roboshop project setup - User
  hosts: USER
  roles:
    - user

- name: roboshop project setup - cart
  hosts: CART
  roles:
    - cart

- name: roboshop project setup - Mysql
  hosts: MYSQL
  roles:
    - mysql

- name: roboshop project setup - shipping
  hosts: SHIPPING
  roles:
    - shipping

- name: roboshop project setup - RabbitMq
  hosts: RABBITMQ
  roles:
    - rabbitmq

- name: roboshop project setup - Payment
  hosts: PAYMENT
  roles:
    - payment

