- name: demo on variables
  hosts: all
  vars:
   URL1: play.google.com
  vars_files: #for loading a file
   - varsfromfile.yml
  tasks: 
   - name: print a variable
     debug: 
      msg: URL = {{URL1}}
   - name: print a variable
     debug: 
      msg: URL = {{URL2}}
   - name: Demo on task level variables
     vars:
      URL3: tasks.google.com
     debug:
      msg: URL = {{URL3}}
   - name: print variable from host file
     debug:
       msg: URL = {{URL4}}