- name: demo on variables
  hosts: all
  vars:
   URL1: play.google.com
   URL: play.google.com
  vars_files: #for loading a file
   - varsfromfile.yml
  tasks: 
   - name: print a variable
     debug: 
      msg: URL = {{URL1}}
   - name: print a variable
     debug: 
      msg: URL = {{URL2}}
   - name: Demo on task level variables
     vars:
      URL3: tasks.google.com
     debug:
      msg: URL = {{URL3}}
   - name: print variable from host file
     debug:
      msg: URL = {{URL4}}
   - name: print variable from command line
     debug:
      msg: URL = {{URL5}}
   - name: Demo on precedance
     vars:
      URL: task.google.com
     debug:
      msg: URL = {{URL}}
   - name: print fact variable
     debug:
      msg: OS = {{ansible_distribution}}
   - name: run a shell command and store output
     shell: uptime
     register: out ## out is a variable that stores uptime
   - name: print uptime output
     debug:
      msg: "{{out.stdout}}" ## in ansible if value starts with a variable it has to be double quoted
   - name: Declare a fact/variable
     set_fact:
      OUTPUT: "{{out.stdout}}"

   - name: print OUTPUT
     debug:
      msg: "{{OUTPUT}}"